name: Build and test

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '~1.24.6', '~1.25.0' ]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... 
  analyze:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.25.0'
      - name: Coverage
        run: go test -v -coverprofile='coverage.out' -coverpkg=./... -json ./... > report.json
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}      